Implement `Process.exePath`
wren-lang/wren-cli pull request #47
Opened 2020-06-19 23:22 UTC by vladimyr

Implement static getter `exePath` for the [`Process` class](http://wren.io/cli/modules/os/process.html).

2021-04-25 20:24 UTC, joshgoebel requested changes

2021-04-25 20:24 UTC, joshgoebel commented on src/module/os.c
> +  char buffer[WREN_PATH_MAX * 2 + 1];
We should really be using `WREN_PATH_MAX` everywhere... does it need to be increased or is there some reason we need much more storage here - in which case I'd suggest we may need another constant vs hard-coding this behavior in multiple places.

2021-04-28 21:56 UTC, closed without merging

2021-04-29 08:26 UTC, vladimyr commented
Hm, ok but we can only guess why? 😕

2021-04-29 13:35 UTC, joshgoebel commented
I believe this needs to be just `Process.path` (simpler naming is our style here), and the other unrelated changes (moving version around) in the PR should be  removed so that it's just this one singular change.  And we don't need to muck with WREN_PATH_MAX, the max path should be more than sufficient.

@vladimyr Would you want to submit an updated PR?